version: '3.7' # Version de Docker
services:
  nginx:
    image: nginx:stable-alpine # Servidor de la aplicacion
    container_name: nginx   # Nombre del servidor
    ports:
      - 8888:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: # Dependencias
      - php
      - mysql
    networks:
      - laravel 

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: admin.root
    ports:
      - 33060:3306  # El valor 3306 es el que tiene por defecto mySql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel

  php:
    image: php:7.4
    build:
      context: .
      dockerfile: Dockerfile

    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80
    networks:
      - laravel  
      
networks:
  laravel:


